// MongoDB Collection Setup
// Generated by rvy
// Note: MongoDB doesn't require migrations like SQL databases,
// but this script can be used to create indexes and validation rules

use mongodb::{
    bson::{doc, Document},
    options::{CreateCollectionOptions, IndexOptions, ValidationAction, ValidationLevel},
    Client, Database,
};

pub async fn create_{{name}}s_collection(db: &Database) -> Result<(), mongodb::error::Error> {
    // Create collection with validation schema
    let validator = doc! {
        "$jsonSchema": doc! {
            "bsonType": "object",
            "required": ["name", "created_at", "updated_at"],
            "properties": doc! {
                "name": doc! {
                    "bsonType": "string",
                    "description": "Name field is required and must be a string"
                },
                "created_at": doc! {
                    "bsonType": "date",
                    "description": "Creation timestamp"
                },
                "updated_at": doc! {
                    "bsonType": "date",
                    "description": "Last update timestamp"
                }
            }
        }
    };

    let options = CreateCollectionOptions::builder()
        .validator(validator)
        .validation_level(ValidationLevel::Moderate)
        .validation_action(ValidationAction::Error)
        .build();

    // Create collection (if it doesn't exist)
    match db.create_collection("{{name}}s", options).await {
        Ok(_) => println!("Collection '{{name}}s' created successfully"),
        Err(e) if e.to_string().contains("already exists") => {
            println!("Collection '{{name}}s' already exists")
        }
        Err(e) => return Err(e),
    }

    // Create index on name field
    let index_model = mongodb::IndexModel::builder()
        .keys(doc! { "name": 1 })
        .options(
            IndexOptions::builder()
                .name("idx_{{name}}s_name".to_string())
                .build(),
        )
        .build();

    db.collection::<Document>("{{name}}s")
        .create_index(index_model, None)
        .await?;

    println!("Index 'idx_{{name}}s_name' created successfully");

    Ok(())
}
