-- Migration: Create {{name}}s table (PostgreSQL)
-- Generated by rvy

CREATE TABLE IF NOT EXISTS {{name}}s (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create index on name for faster lookups
CREATE INDEX IF NOT EXISTS idx_{{name}}s_name ON {{name}}s(name);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_{{name}}s_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_{{name}}s_updated_at
    BEFORE UPDATE ON {{name}}s
    FOR EACH ROW
    EXECUTE FUNCTION update_{{name}}s_updated_at();
