-- Migration: Create {{name}}s table (SQLite)
-- Generated by rvy

CREATE TABLE IF NOT EXISTS {{name}}s (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_{{name}}s_name ON {{name}}s(name);

-- Trigger to auto-update updated_at
CREATE TRIGGER IF NOT EXISTS update_{{name}}s_updated_at
    AFTER UPDATE ON {{name}}s
    FOR EACH ROW
BEGIN
    UPDATE {{name}}s SET updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.id;
END;
